files:
  keys: "code/BE22-01_artMS_keys.txt"
  contrasts: "code/BE22-01_artMS_contrasts.txt"
  evidence: "results/MaxQuant/evidence_uniqueOnly.txt"
  summary: "results/MaxQuant/summary.txt"
  output: "results/artMS/artMS_results.txt"
qc:
  basic: 0
  extended: 0
  extendedSummary: 0
data:
  enabled: 1
  fractions:
    enabled: 0
  silac:
    enabled: 0
  filters:
    enabled: 1
    contaminants: 1
    protein_groups: remove
    modifications: AB
  sample_plots: 1
msstats:
  enabled: 1
  msstats_input: ~
  profilePlots: none
  normalization_method: quantile
  normalization_reference: ~
  summaryMethod: TMP
  censoredInt: NA
  cutoffCensored: minFeature
  MBimpute: 1
  feature_subset: all
output_extras:
  enabled: 1
  annotate:
    enabled: 1
    species: YEAST
  plots:
    volcano: 1
    heatmap: 1
    LFC: -1 1
    FDR: 0.05
    heatmap_cluster_cols: 1
    heatmap_display: log2FC
